### ISSUE TITLE
Requests not working with requests-cache session

### ISSUE THREAD

**Issue by simonanez** [pydata/pandas-datareader#417] opened 2017-11-03 23:28 UTC
From the docs: https://pandas-datareader.readthedocs.io/en/latest/cache.html
```
import pandas_datareader.data as web
import datetime
import requests_cache

expire_after = datetime.timedelta(days=3)
session = requests_cache.CachedSession(cache_name='cache', backend='sqlite', expire_after=expire_after)
start = datetime.datetime(2010, 1, 1)
end = datetime.datetime(2013, 1, 27)
f = web.DataReader("F", 'yahoo', start, end, session=session)
```

Error                                     Traceback (most recent call last)
<ipython-input-170-98044cbebe88> in <module>()
      7 start = datetime.datetime(2010, 1, 1)
      8 end = datetime.datetime(2013, 1, 27)
----> 9 f = web.DataReader("F", 'yahoo', start, end, session=session)

e:\Anaconda2\lib\site-packages\pandas_datareader\data.pyc in DataReader(name, data_source, start, end, retry_count, pause, session, access_key)
    119                                 adjust_price=False, chunksize=25,
    120                                 retry_count=retry_count, pause=pause,
--> 121                                 session=session).read()
    122 
    123     elif data_source == "yahoo-actions":

e:\Anaconda2\lib\site-packages\pandas_datareader\yahoo\daily.pyc in __init__(self, symbols, start, end, retry_count, pause, session, adjust_price, ret_index, chunksize, interval)
     80 
     81         self.interval = '1' + self.interval
---> 82         self.crumb = self._get_crumb(retry_count)
     83 
     84     @property

e:\Anaconda2\lib\site-packages\pandas_datareader\yahoo\daily.pyc in _get_crumb(self, retries)
    156         tu = "https://finance.yahoo.com/quote/{}/history".format(self.symbols)
    157         response = self._get_response(tu,
--> 158                                       params=self.params, headers=self.headers)
    159         out = str(self._sanitize_response(response))
    160         # Matches: {"crumb":"AlphaNumeric"}

e:\Anaconda2\lib\site-packages\pandas_datareader\base.pyc in _get_response(self, url, params, headers)
    124             response = self.session.get(url,
    125                                         params=params,
--> 126                                         headers=headers)
    127             if response.status_code == requests.codes.ok:
    128                 return response

e:\Anaconda2\lib\site-packages\requests\sessions.pyc in get(self, url, **kwargs)
    499             prep.url, proxies, stream, verify, cert
    500         )
--> 501 
    502         # Send the request.
    503         send_kwargs = {

e:\Anaconda2\lib\site-packages\requests_cache\core.pyc in request(self, method, url, params, data, **kwargs)
    124             _normalize_parameters(params),
    125             _normalize_parameters(data),
--> 126             **kwargs
    127         )
    128         if self._is_cache_disabled:

e:\Anaconda2\lib\site-packages\requests\sessions.pyc in request(self, method, url, params, data, headers, cookies, files, auth, timeout, allow_redirects, proxies, hooks, stream, verify, cert, json)
    486             files=files,
    487             data=data or {},
--> 488             json=json,
    489             params=params or {},
    490             auth=auth,

e:\Anaconda2\lib\site-packages\requests_cache\core.pyc in send(self, request, **kwargs)
     97         response, timestamp = self.cache.get_response_and_time(cache_key)
     98         if response is None:
---> 99             return send_request_and_cache_response()
    100 
    101         if self._cache_expire_after is not None:

e:\Anaconda2\lib\site-packages\requests_cache\core.pyc in send_request_and_cache_response()
     89 
     90         def send_request_and_cache_response():
---> 91             response = super(CachedSession, self).send(request, **kwargs)
     92             if response.status_code in self._cache_allowable_codes:
     93                 self.cache.save_response(cache_key, response)

e:\Anaconda2\lib\site-packages\requests\sessions.pyc in send(self, request, **kwargs)
    607         allow_redirects = kwargs.pop('allow_redirects', True)
    608         stream = kwargs.get('stream')
--> 609         hooks = request.hooks
    610 
    611         # Get the appropriate adapter to use

e:\Anaconda2\lib\site-packages\requests\adapters.pyc in send(self, request, stream, timeout, verify, cert, proxies)
    421                        "both timeouts to the same value".format(timeout))
    422                 raise ValueError(err)
--> 423         elif isinstance(timeout, TimeoutSauce):
    424             pass
    425         else:

e:\Anaconda2\lib\site-packages\requests\packages\urllib3\connectionpool.pyc in urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)

e:\Anaconda2\lib\site-packages\requests\packages\urllib3\connectionpool.pyc in _make_request(self, conn, method, url, timeout, chunked, **httplib_request_kw)

e:\Anaconda2\lib\site-packages\requests\packages\urllib3\connectionpool.pyc in _validate_conn(self, conn)

e:\Anaconda2\lib\site-packages\requests\packages\urllib3\connection.pyc in connect(self)

e:\Anaconda2\lib\site-packages\requests\packages\urllib3\util\ssl_.pyc in ssl_wrap_socket(sock, keyfile, certfile, cert_reqs, ca_certs, server_hostname, ssl_version, ciphers, ssl_context, ca_cert_dir)

e:\Anaconda2\lib\site-packages\requests\packages\urllib3\contrib\pyopenssl.pyc in load_verify_locations(self, cafile, capath, cadata)

e:\Anaconda2\lib\site-packages\OpenSSL\SSL.pyc in load_verify_locations(self, cafile, capath)
    523         )
    524         if not load_result:
--> 525             _raise_current_error()
    526 
    527     def _wrap_callback(self, callback):

e:\Anaconda2\lib\site-packages\OpenSSL\_util.pyc in exception_from_error_queue(exception_type)
     46             text(lib.ERR_reason_error_string(error))))
     47 
---> 48     raise exception_type(errors)
     49 
     50 

Error: [('system library', 'fopen', 'No such file or directory'), ('BIO routines', 'BIO_new_file', 'no such file'), ('x509 certificate routines', 'X509_load_cert_crl_file', 'system lib')]

**Comment by simonanez** [comment] 2017-11-03 23:39
Looks like i get the same error without using session, but data.get_data_google seems to be working, maybe i'm banned from Yahoo?

**Comment by nglgzz** [comment] 2017-11-06 16:20
I had the same problem, searching around seems like Yahoo shut down their API.

**Comment by bashtage** [comment] 2018-01-10 11:43
Closing since dupe of other Yahoo issues.

**Closed by bashtage** 2018-01-10 11:43 UTC
