### ISSUE TITLE
'YahooDailyReader'

### ISSUE THREAD

**Issue by chemalle** [pydata/pandas-datareader#333] opened 2017-05-17 20:24 UTC
Hi people,

Anyone know if Yahoo is not providing data anymore? Since yesterday I can not retrieve any data from pandas web data reader.

Thank you!

**Comment by rgkimball** [comment] 2017-05-17 23:20
Their API changed a bit, hang tight for a fix. See #315 for discussion/details.

**Comment by thsavage** [comment] 2017-05-18 01:11
Has the Yahoo API changed "a bit" or has it been discontinued?

**Comment by rgkimball** [comment] 2017-05-18 01:14
It is still accessible, but they've substantially modified the endpoints and implemented a mandatory cookie. I'm still unclear on how to provide access for certain data (namely options and index constituents), but historical prices, dividends and splits are available.

**Comment by jreback** [comment] 2017-07-02 15:09
dupe of #315

**Closed by jreback** 2017-07-02 15:09 UTC
