### ISSUE TITLE
Yahoo will be right back

### ISSUE THREAD

**Issue by hmz123** [pydata/pandas-datareader#338] opened 2017-05-18 21:09 UTC
I think yahoo they are changing the structure of the site .
So, is there a solution for download data?
What do I have to do?

raise RemoteDataError('Unable to read URL: {0}'.format(url))
pandas_datareader._utils.RemoteDataError: Unable to read URL: http://ichart.finance.yahoo.com/table.csv?a=0&ignore=.csv&s=aapl&b=1&e=1&d=0&g=d&f=2014&c=2013

**Comment by jasonstrimpel** [comment] 2017-05-19 00:18
Looks like the new link is https://query1.finance.yahoo.com/v7/finance/download/GS?period1=1492561103&period2=1495153103&interval=1d&events=history&crumb=NCkOXP2wSVV

It also looks like you need the crumb cookie session or you get an unauthorized.

**Comment by chriddyp** [comment] 2017-05-19 16:12
Some related discussion from the R world: https://github.com/joshuaulrich/quantmod/issues/157

**Comment by chriddyp** [comment] 2017-05-19 16:12
See https://github.com/pydata/pandas-datareader/issues/315

**Comment by ranaroussi** [comment] 2017-05-22 06:25
I've created a library that offers a work-around that offers a temporary solution to the problem:
https://github.com/ranaroussi/fix-yahoo-finance

Maybe ``pandas_datareader`` can use some of its code?

**Comment by manuelaguilar** [comment] 2017-05-29 04:37
@ranaroussi Thanks, this fixes the issue temporarily. 

Will this or any other solution be integrated in datareader for Yahoo?

**Comment by toddpi314** [comment] 2017-06-08 13:32
@ranaroussi="The hero we all deserve"

**Comment by jreback** [comment] 2017-07-02 15:09
dupe of #315

**Closed by jreback** 2017-07-02 15:09 UTC
