### ISSUE TITLE
Error converting YahooActionReader to DataFrame

### ISSUE THREAD

**Issue by zechzhao** [pydata/pandas-datareader#761] opened 2020-03-19 23:38 UTC
I was attempting to download data to make sense of adjusted prices.

To download the split and dividend data from Yahoo, I used 

`pandas_datareader.yahoo.actions.YahooActionReader (ticker, start, end, get_actions=True)`

and 

`pandas_datareader.yahoo.daily.YahooDailyReader(ticker, start, end, get_actions=True)`

Both of them seemed receiving the data fine, however, when converting the data to DataFrame both run into the same error:

```
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pandas_datareader/yahoo/daily.py", line 201, in split_ratio
    return eval(row["Splitratio"])

  File "<string>", line 1
    2:1

```
I'm not sure if `read()` was a possible way to covert the information to DataFrame, but it seems to be the only member function that looks like performing such a job.

**Comment by zechzhao** [comment] 2020-03-20 16:22
I managed to perform my adjusted price calculation from data on Tiingo.

However, why the yahoo package is not working as expected perhaps still worth looking into.

**Comment by lz-chen** [comment] 2020-06-10 09:17
I was having the same problem and manage to solve it by changing 
```
                def split_ratio(row):
                    if float(row["Numerator"]) > 0:
                        return eval(row["Splitratio"])
                    else:
                        return 1
```
to 
```
                def split_ratio(row):
                    if float(row["Numerator"]) > 0:
                        return row["Splitratio"] # not using eval()
                    else:
                        return 1
```
in `pandas_datareader/yahoo/daily.py", line 201, in split_ratio`

This seems to be a bug that needs fixing?

**Comment by ParkAvenueSoftwareAndArt** [comment] 2020-07-11 04:37
This is a dupe of 
https://github.com/pydata/pandas-datareader/issues/755

which is fixed.

**Closed** 2020-07-11 06:13 UTC
