### ISSUE TITLE
Pandas data reader for google  end dates are not working 

### ISSUE THREAD

**Issue by nithints** [pydata/pandas-datareader#395] opened 2017-09-16 05:58 UTC
import pandas_datareader.data as web
 import datetime
 start = datetime.datetime(2010, 1, 1)

 end = datetime.datetime(2015, 5, 9)

 web.DataReader('AAPL', 'google', start, end)

getting an year data irrespective of start and end dates
![image](https://user-images.githubusercontent.com/6574109/30509594-270f6644-9ad2-11e7-9999-205e5aed5811.png)

**Comment by rsvp** [comment] 2017-09-16 16:41
- [ ] **Duplicate** issue of #391 and #394

**Comment by bkcollection** [comment] 2017-09-23 09:13
@rsvp  Is the google historical data is just merely a change of link from www.google.com to finance.google.com ?
or it has a more complicated issues to deal with before merge into pandas-datareader? If it is stopped will cause a big issues for non US user as we do not have any alternatives which is need to cost a lot of money like Bloomberg/reuters

**Comment by rsvp** [comment] 2017-09-23 17:21
@bkcollection I have covered both *Google Finance URL Change* and *Alternative Data Sources* at https://github.com/rsvp/fecon235/issues/7 in detail. The situation is still in flux.

**Comment by 1rocketdude** [comment] 2017-09-24 01:42
thank you for the thorough description of the problem with Google and
Yahoo. I've had good luck with Quandl, but it is not infallible. Some
symbols are not available. Have not tried Tingo and Alpha Advantage, so I
have no experience.

Looks like time to ditch Google and Yahoo. Frequent interface changes are
challenging to keep up with.

**Comment by innocentkithinji** [comment] 2017-10-16 18:44
It is easy to fix just change the googles daily.py file to look llike [this one](https://github.com/pydata/pandas-datareader/blob/master/pandas_datareader/google/daily.py).
The reason it doesnt fetch the data is that google changed its finance url from http://www.google.com/finance/historical to http://finance.google.com/finance/historical during the redirect the dates are not passed in the HTTP request.

**Comment by EngJay** [comment] 2017-11-12 18:11
I just ran into this issue with version 0.5.0 and confirmed that the fix suggested above by @innocentkithinji does restore expected functionality.

**Comment by davidastephens** [comment] 2017-12-10 22:16
Fixed in #404

**Closed by davidastephens** 2017-12-10 22:16 UTC
