### ISSUE TITLE
PARSE ERROR

### ISSUE THREAD

**Issue by praveenvaddimgunta** [pydata/pandas-datareader#343] opened 2017-05-26 11:05 UTC
When I am using pandas-datareader to fetch the Oanda currency historical rate using the following code

**from pandas_datareader.oanda import get_oanda_currency_historical_rates
start, end = "2016-01-01", "2016-06-01"
quote_currency = "USD"
base_currency = ["EUR", "GBP", "JPY"]
df_rates = get_oanda_currency_historical_rates(
start, end,
quote_currency=quote_currency,
base_currency=base_currency
)
print(df_rates)**

I am getting the following error
**ParserError: ',' expected after '"'. Error could possibly be due to parsing errors in the skipped footer rows (the skipfooter keyword is only applied after Python's csv library has parsed all rows).**

**Comment by talwrii** [comment] 2017-06-21 23:20
**Possible duplicate of **" https://github.com/pydata/pandas-datareader/issues/296.

I'm note quite sure if it is the same: there is no mention of `ParseError`, though we do have 

    Error: ',' expected after '"'

This bug says:

     OANDA now displays on their website
     Register to become a Premium Member

**Comment by gliptak** [comment] 2017-07-10 19:45
@praveenvaddimgunta Support for Oanda was removed with https://github.com/pydata/pandas-datareader/pull/366 Consider closing this issue

**Closed** 2017-07-10 20:07 UTC
