### ISSUE TITLE
Yahoo Finance data broken again

### ISSUE THREAD

**Issue by AlexAlifimoff** [pydata/pandas-datareader#354] opened 2017-06-26 17:21 UTC
Hi folks,

Yahoo Finance appears to be broken. [The examples on the Yahoo! Finance readthedocs page](https://pandas-datareader.readthedocs.io/en/latest/remote_data.html#yahoo-finance) fail as provided. If I understand correctly, the last time this happened it had something to do with changes to the API itself. I'm not sure if the API was totally phased out, but it definitely doesn't work as is.

**Comment by EAlpha83** [comment] 2017-06-26 21:04
I am facing the same issue. I believe there was a fix in the version 0.4.1 but I no longer see that version anywhere. Help will be appreciated.

**Comment by musiclicn** [comment] 2017-06-28 12:07
I have same issue. In addition, google finance is broken because of Robot check. There is no data available now. Could someone fix it since this library is not working.

**Comment by jreback** [comment] 2017-06-28 12:32
this is a dupe of #315

pr to fix is in #331 though needs some attention

**Closed by jreback** 2017-06-28 12:32 UTC
