### ISSUE TITLE
Docs bug

### ISSUE THREAD

**Issue by andportnoy** [pydata/pandas-datareader#197] opened 2016-04-24 09:22 UTC
The [usage examples](http://pandas-datareader.readthedocs.org/en/latest/remote_data.html#yahoo-finance-options) for Yahoo Finance options contain a couple errors.

**Comment by femtotrader** [comment] 2016-04-24 09:45
Thanks for reporting this issue.
But I think it's a duplicate of https://github.com/pydata/pandas-datareader/issues/150

**Closed** 2016-04-24 09:48 UTC

**Comment by andportnoy** [comment] 2016-04-24 09:55
Oh, that's right. I'll see if I can replicate the error.

**Comment by femtotrader** [comment] 2016-04-24 09:55
Thanks
