### ISSUE TITLE
Having weird issues with the data reader fetching yahoo finance 

### ISSUE THREAD

**Issue by xrlu0929** [pydata/pandas-datareader#332] opened 2017-05-17 20:19 UTC
`import pandas_datareader as pdr
import pandas as pd

import matplotlib.pyplot as plt

import datetime as dt
start_date = dt.datetime(2016,1,1)
end_date = dt.datetime(2016,12,31)
df_bit = pdr.get_data_yahoo('GBTC', start_date, end_date)
df_gd = pdr.get_data_yahoo('IAU', start_date, end_date)
df_com = pdr.get_data_yahoo('IYZ', start_date, end_date)
df_bio = pdr.get_data_yahoo('RYOIX', start_date, end_date)
df_tao = pdr.get_data_yahoo('TAO', start_date, end_date)
df_sp = pdr.get_data_yahoo('^GSPC', start_date, end_date)`

Then it returns：
`---------------------------------------------------------------------------
RemoteDataError                           Traceback (most recent call last)
<ipython-input-4-3773d2c3f242> in <module>()
----> 1 df_bit = pdr.get_data_yahoo('GBTC', start_date, end_date)
      2 df_gd = pdr.get_data_yahoo('IAU', start_date, end_date)
      3 df_com = pdr.get_data_yahoo('IYZ', start_date, end_date)
      4 df_bio = pdr.get_data_yahoo('RYOIX', start_date, end_date)
      5 df_tao = pdr.get_data_yahoo('TAO', start_date, end_date)

/Users/annaxlu/anaconda3/lib/python3.6/site-packages/pandas_datareader/data.py in get_data_yahoo(*args, **kwargs)
     38 
     39 def get_data_yahoo(*args, **kwargs):
---> 40     return YahooDailyReader(*args, **kwargs).read()
     41 
     42 

/Users/annaxlu/anaconda3/lib/python3.6/site-packages/pandas_datareader/yahoo/daily.py in read(self)
     74     def read(self):
     75         """ read one data from specified URL """
---> 76         df = super(YahooDailyReader, self).read()
     77         if self.ret_index:
     78             df['Ret_Index'] = _calc_return_index(df['Adj Close'])

/Users/annaxlu/anaconda3/lib/python3.6/site-packages/pandas_datareader/base.py in read(self)
    153         # If a single symbol, (e.g., 'GOOG')
    154         if isinstance(self.symbols, (compat.string_types, int)):
--> 155             df = self._read_one_data(self.url, params=self._get_params(self.symbols))
    156         # Or multiple symbols, (e.g., ['GOOG', 'AAPL', 'MSFT'])
    157         elif isinstance(self.symbols, DataFrame):

/Users/annaxlu/anaconda3/lib/python3.6/site-packages/pandas_datareader/base.py in _read_one_data(self, url, params)
     72         """ read one data from specified URL """
     73         if self._format == 'string':
---> 74             out = self._read_url_as_StringIO(url, params=params)
     75         elif self._format == 'json':
     76             out = self._get_response(url, params=params).json()

/Users/annaxlu/anaconda3/lib/python3.6/site-packages/pandas_datareader/base.py in _read_url_as_StringIO(self, url, params)
     83         Open url (and retry)
     84         """
---> 85         response = self._get_response(url, params=params)
     86         text = self._sanitize_response(response)
     87         out = StringIO()

/Users/annaxlu/anaconda3/lib/python3.6/site-packages/pandas_datareader/base.py in _get_response(self, url, params)
    118         if params is not None and len(params) > 0:
    119             url = url + "?" + urlencode(params)
--> 120         raise RemoteDataError('Unable to read URL: {0}'.format(url))
    121 
    122     def _read_lines(self, out):

RemoteDataError: Unable to read URL: http://ichart.finance.yahoo.com/table.csv?s=GBTC&a=0&b=1&c=2016&d=11&e=31&f=2016&g=d&ignore=.csv
`

**Comment by rgkimball** [comment] 2017-05-17 20:20
You're not alone... see #315, #330 and PR #331

**Comment by xrlu0929** [comment] 2017-05-17 20:24
@rgkimball Oh My.... I've tried searching for new tickers, and even restart...but no.. It worked yesterday, just today when I wanted to look into some issues to finalize it, then it shows like this!
Thanks, I'll go and see the issues you mentioned to try luck.

**Comment by jreback** [comment] 2017-07-02 15:09
dupe of #315

**Closed by jreback** 2017-07-02 15:09 UTC
